#!/usr/bin/env node
// Derives spec/vocab/*.map.json from the dependency map's vocabulary nodes and
// writes spec/schemas/vocab.schema.json, one enum per closed list, from the
// map copies and from local.json.
//
// The map (tools/depmap/graph.json) is checked against the pages by
// `node tools/depmap.mjs check`, so a list copied from the map is transitively
// checked against the publication. This script copies; test/vocab.test.mjs
// fails when a copy or the enum schema has drifted, so the three cannot
// disagree silently. Run it after a map change or an edit to local.json:
//
//   node spec/vocab/derive.mjs
//
// Lists the map does not carry as vocabulary nodes live in local.json, each
// with the page locus it was read from; they are not map-checked.
import { readFileSync, writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const graphPath = join(here, '..', '..', 'tools', 'depmap', 'graph.json');
const schemaPath = join(here, '..', 'schemas', 'vocab.schema.json');

export function deriveVocabularies(graph) {
  const out = [];
  for (const node of graph.nodes) {
    if (node.kind !== 'vocab') continue;
    const canonical = (node.loci || []).find((l) => l.role === 'canonical');
    out.push({
      id: node.id,
      slug: node.id.replace(/^vocab-/, ''),
      label: node.label,
      source: 'tools/depmap/graph.json',
      canonical: canonical ? canonical.at : null,
      check: node.check || 'members',
      members: (node.members || []).map((m) => {
        const member = { id: m.id, word: m.word };
        if (m.code !== undefined) member.code = m.code;
        if (m.alt !== undefined) member.alt = m.alt;
        return member;
      }),
    });
  }
  return out;
}

export function enumSchema(members, label, canonical) {
  const fixed = members.filter((m) => !m.pattern).map((m) => m.id);
  const patterns = members.filter((m) => m.pattern).map((m) => ({ type: 'string', pattern: m.pattern }));
  const base = { description: label, 'x-locus': canonical };
  if (patterns.length === 0) return { ...base, type: 'string', enum: fixed };
  return { ...base, anyOf: [{ type: 'string', enum: fixed }, ...patterns] };
}

export function buildVocabSchema(mapped, localFile) {
  const $defs = {};
  for (const v of mapped) $defs[v.slug] = enumSchema(v.members, v.label, v.canonical);
  for (const [slug, v] of Object.entries(localFile.vocabularies)) {
    if ($defs[slug]) throw new Error(`local vocabulary "${slug}" collides with a map vocabulary`);
    $defs[slug] = enumSchema(v.members, v.label, v.canonical);
  }
  return {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'aifred:vocab',
    title: 'Closed lists',
    description: 'One enum per closed list. Generated by spec/vocab/derive.mjs from the map copies and local.json; never edited by hand.',
    $defs,
  };
}

export function loadGraph() {
  return JSON.parse(readFileSync(graphPath, 'utf8'));
}

export function loadLocal() {
  return JSON.parse(readFileSync(join(here, 'local.json'), 'utf8'));
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const derived = deriveVocabularies(loadGraph());
  for (const f of readdirSync(here)) {
    if (f.endsWith('.map.json')) unlinkSync(join(here, f));
  }
  for (const v of derived) {
    writeFileSync(join(here, `${v.slug}.map.json`), JSON.stringify(v, null, 2) + '\n');
  }
  writeFileSync(schemaPath, JSON.stringify(buildVocabSchema(derived, loadLocal()), null, 2) + '\n');
  console.log(`wrote ${derived.length} vocabularies from the map and ${schemaPath}`);
}
